### ISSUE TITLE
Add header view instead image

### ISSUE THREAD

**Issue by ezeperez26** [Codeido/PMAlertController#15]
A UIView is more flexible for show dynamic information besides the title and text.
The height of header view could be flexible.

Thanks for the great library!

**Comment by Codeido** [comment]
Hi @ezeperez26.
Are you telling me to insert an UIView, containing the image of header? Right?

Thanks
P

**Comment by ezeperez26** [comment]
Hi,
Yes, is more flexible, for example, to add animated view. Also adjusts height automatically with autolayout.

See my implementation of header view and simple animation example in [my fork](https://github.com/ezeperez26/PMAlertController/tree/header-view).

Thanks

**Comment by Codeido** [comment]
Hi @ezeperez26, sorry for the delay.
It's not a bad idea, but i think that we can introduce this change directly in the swift 3 version of PMAlertController.
There is a branch for swift 3: https://github.com/Codeido/PMAlertController/tree/swift3
then you can open a pull request on this branch ;)

Thanks
-Paolo

**Comment by hons82** [comment]
I'd need for an App an Alert with a header view that I can change over time...
Basically a progress view

**Comment by Codeido** [comment]
Hi @hons82, try to see the forked branch of @ezeperez26. You can find it here: https://github.com/ezeperez26/PMAlertController/tree/header-view and you can use cocoapods to install it.
We want to introduce header in the swift 3 branch soon.

**Comment by Codeido** [comment]
You can find this enhancement here: https://github.com/Codeido/PMAlertController/commit/09fd2e0de3cdcee0574a91c0e3bbc1a4eac0571b

**Comment by ezeperez26** [comment]
Great! Thanks!
