### ISSUE TITLE
Changing background color of an alert

### ISSUE THREAD

**Issue by tomqz** [Codeido/PMAlertController#16]
Hi!
I'm trying to change the background color of the alert - can i achieve this with the property "alertMaskBackground"? If so... then it doesn't work - or maybe I don't know how to use it. Can You post some example?

Thanks for the great lib!

**Comment by Codeido** [comment]
Hi @tomqz, 
you can use the property alertView:
alertVC.alertView.backgroundColor = UIColor.redColor()

Let me know.
Thanks
-Paolo

**Comment by tomqz** [comment]
Yep, it works 👍  Didn't notice the alertView property.
Thanks for the quick response! Can You tell me, what is for alertMaskBackground?

**Comment by Codeido** [comment]
alertMaskBackground is a UIImageView that works like a background for the alert (a layer over the content)

**Comment by tomqz** [comment]
Maybe I did something wrong, but imageView didn't work for me with the alertMaskBackground.. Anyway, thanks for the help!
