### ISSUE TITLE
must ios 9.0?

### ISSUE THREAD

**Issue by arden** [Codeido/PMAlertController#2]
the ios version must 9.0?

**Comment by barnaclejive** [comment]
iOS 8 support would be great, but there will need to be some alternate way to reference the autoLayout guides and anchors.

![errors](https://cloud.githubusercontent.com/assets/5251331/15374162/a0c99db2-1d0e-11e6-8f28-7964b2441867.jpg)

**Comment by arden** [comment]
https://github.com/tomvanzummeren/TZStackView
The TAStackView could down to 8.0, like UIStackView.

**Comment by Codeido** [comment]
In October the majority of developers will abandon iOS 8.
I believe that the advantages of bringing the library to a compatibility with iOS 8 using external libraries, create only entropy in this case. Currently iOS 9 has an adoption of 84%.

However, if you want to use PMAlertController in iOS 8 you can create and use a fork where you can use TAStackView library, but you need to substitute UILayoutGuide.
