### ISSUE TITLE
objectiv-c compatibilities

### ISSUE THREAD

**Issue by jeromeMorjon** [Codeido/PMAlertController#20]
Can't call method init with objectiv-c.
any issue?

**Comment by Codeido** [comment]
Hi Jerome, try to see this issue https://github.com/Codeido/PMAlertController/issues/4 where i explain how to use PMAlertController with Objective-C.

**Comment by jeromeMorjon** [comment]
i saw this post, but i can't call the method init as this issue...

**Comment by Codeido** [comment]
Is your pod updated to the last release version?
I think that a possible problem is imputable to the bridge file, that is not created in the correct way. I tested now the last release of the library with obj-c, and is working.

**Comment by jeromeMorjon** [comment]
effectively, now it's ok !
I was on cocoa pod v1.0.0. or now is 1.0.4 and all is ok ;)

thx you 👍

**Comment by vsanthanam** [comment]
For people who are still looking for better Objective-C compatibility, I re-wrote this entire library in Objective-C, with a few other features and without the need for an .xib file
