### ISSUE TITLE
Use of unresolved identifier 'PMAlertController'

### ISSUE THREAD

**Issue by JamesGDEv** [Codeido/PMAlertController#25]
I dragged the **/Library** folder to the Project Navigation.

Then added this code:

       let alertVC = PMAlertController(title: "A Title", description: "My Description", image: UIImage(named: "img.png"), style: .Alert)
        
        alertVC.addAction(PMAlertAction(title: "Cancel", style: .Cancel, action: { () -> Void in
            print("Capture action Cancel")
        }))
        
        alertVC.addAction(PMAlertAction(title: "OK", style: .Default, action: { () in
            print("Capture action OK")
        }))
        
        self.presentViewController(alertVC, animated: true, completion: nil)

to my ViewController. 

However, I get this error:

> Use of unresolved identifier 'PMAlertController'

**Comment by Codeido** [comment]
Hi @JamesGDEv.

I think that you have to set the target for the library, like that:
![w49az](https://cloud.githubusercontent.com/assets/495617/18303957/f614e78a-74df-11e6-8604-14d8ffe5724b.png)

Let me know.
Thanks
-Paolo
