### ISSUE TITLE
Swift 3 Support is missing ? 

### ISSUE THREAD

**Issue by YHSX88** [Codeido/PMAlertController#26]
Hi 

I love the library but I don't think it has Swift 3 support as Xcode 8 is telling me that I need to do a lot of changes. 

for example:
 //MARK: - Customizations
    @objc private func setShadowAlertView(){
        alertView.layer.masksToBounds = false
        alertView.layer.shadowOffset = CGMake(0,0) _**and should be**_ CGSize(width: 0, height: 0)
        alertView.layer.shadowRadius = 8
        alertView.layer.shadowOpacity = 0.3
    }

What I'm missing ?

**Comment by Codeido** [comment]
Hi @YHSX88.
Are you using the correct branch of the library?

The master branch actually support swift 2.3. If you need swift 3.0, you have to use this https://github.com/Codeido/PMAlertController/tree/swift3

You can use it via cocoapods:
```
pod 'PMAlertController', :git => https://github.com/Codeido/PMAlertController', :branch => 'swift3'
```

**Comment by YHSX88** [comment]
Hi Codeido
I got this message with the pod you gave me ?

[!] Invalid `Podfile` file: syntax error, unexpected tLABEL
...lertController', :git => https://github.com/Codeido/PMAlertC...
...                               ^
/Users/OSX/Documents/SDD/Xcode8_projects/PMtest_SW3/Podfile:5: unknown regexp options - gthb
/Users/OSX/Documents/SDD/Xcode8_projects/PMtest_SW3/Podfile:5: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
....com/Codeido/PMAlertController', :branch => 'swift3'
...                               ^
/Users/OSX/Documents/SDD/Xcode8_projects/PMtest_SW3/Podfile:5: syntax error, unexpected tIDENTIFIER, expecting end-of-input
...Controller', :branch => 'swift3'
...                               ^.

**Comment by Codeido** [comment]
Ops, try again now, I modified the string of my previous comment.

**Comment by YHSX88** [comment]
On empty project when I did pod install with the link provided Xcode 8 is giving me still suggestion to change to Swift 3


![screen shot 2016-09-17 at 18 16 33](https://cloud.githubusercontent.com/assets/16823745/18609119/ed076908-7d02-11e6-9bfe-03a6079d04c4.png)

**Comment by Codeido** [comment]
Porting to swift 3 is not yet 100% complete.
I'll do an update on the branch in a few minutes. I will alert you here.

**Comment by YHSX88** [comment]
Thank you, and you know sorry for this but in the description is saying Support of Swift 2.3 and 3 

Thank you in advance.

**Comment by Codeido** [comment]
Hi @YHSX88, try now.

Thanks
-Paolo

**Comment by YHSX88** [comment]
Ok Just did it 
and I got the message from xcode to convert to swift 3 but then xcode found no changes to make
but after this  I still got 64 errors.

![screen shot 2016-09-17 at 18 36 31](https://cloud.githubusercontent.com/assets/16823745/18609231/dd538f5c-7d05-11e6-8f90-d745a6d6531d.png)

![screen shot 2016-09-17 at 18 36 49](https://cloud.githubusercontent.com/assets/16823745/18609234/e0d6013c-7d05-11e6-84c2-e016cc7f9639.png)

**Comment by YHSX88** [comment]
And this is the podfile text

platform :ios, '9.0'
use_frameworks!

target 'PM_SW3' do

  
pod 'PMAlertController', :git => 'https://github.com/Codeido/PMAlertController', :branch => 'swift3'

end

**Comment by Codeido** [comment]
Oh, i see that your project need an update to the recommended settings. Do it, and retry.

Make sure that in Build Settings there are these two options
![schermata 2016-09-17 alle 17 45 39](https://cloud.githubusercontent.com/assets/495617/18609272/98f0ad06-7cfe-11e6-8f13-06a3d79f404f.png)

and

![schermata 2016-09-17 alle 17 46 08](https://cloud.githubusercontent.com/assets/495617/18609275/a6e215da-7cfe-11e6-8493-14ba5f320af4.png)

**Comment by Codeido** [comment]
I think that another reason can be the settings of Cocoapods (i tryed now the library on another project and is working).

Try to insert in your podfile this:


``
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
``

**Comment by YHSX88** [comment]
It is working with the first suggestion however not sure why but I don't have setting exactly as you 
do i.e. **SWIFT_VERSION** I do have this:

![screen shot 2016-09-17 at 18 53 34](https://cloud.githubusercontent.com/assets/16823745/18609323/0e70cd6e-7d08-11e6-9634-608a8335c0a6.png)

**Comment by YHSX88** [comment]
Any way thanks a lot :)

**Comment by Codeido** [comment]
Excellent 👍
In the first case it was an error inside the library. In the second case was an error of configuration of the project.

Thanks for your contribution @YHSX88 ;)
-Paolo

**Comment by YHSX88** [comment]
Aaah just to ask you,  for anybody out there when do you plan to move swift 3 on the master branch ?

**Comment by Codeido** [comment]
Barring unforeseen circumstances, tomorrow, and i want to integrate this https://github.com/Codeido/PMAlertController/issues/15 as a new feature.

**Comment by YHSX88** [comment]
Great :)

**Comment by Codeido** [comment]
The new version compatible with Swift 3 is now on master branch and is available on cocoapods.
https://github.com/Codeido/PMAlertController/commit/f73c944ebf3b15769c4207795e432b5fa19fb1a3

**Comment by YHSX88** [comment]
Hi thanks for this !

I just tried to install via podfile -> pod 'PMAlertController'
and it is downloading ver 1.1.0:

![screen shot 2016-09-19 at 08 45 46](https://cloud.githubusercontent.com/assets/16823745/18623492/764713be-7e46-11e6-8442-8c5357277e9d.png)

then I tried to get it from the master and I got it:

![screen shot 2016-09-19 at 08 53 47](https://cloud.githubusercontent.com/assets/16823745/18623505/a1b8e1b2-7e46-11e6-9633-455191fca092.png)

Then it gave me many errors like 64 in count,  but I just recompiled and it is working JUST FINE now.

This is for anybody out there.
