### ISSUE TITLE
Error like Required Xcode 8.0 in Version 1.1.0

### ISSUE THREAD

**Issue by rp9994** [Codeido/PMAlertController#30]
I have install PMAlertController in version 1.1.0 in Xcode 7.3 and Deployment target is 9.0 but the issue is something like this : 
`"This Version does not support documents save in the Xcode 8 format. Open this document with Xcode 8.0 or later."`

**Comment by Codeido** [comment]
Hi @rp9994. The release 1.1.0 of PMAlertController works with Swift 3, and swift 3 is supported only from Xcode > 8.x. I suggest you to update your Xcode installation.
