### ISSUE TITLE
Blackscreen when goes back to alert controller using tab bar ?

### ISSUE THREAD

**Issue by fadylateef** [Codeido/PMAlertController#31]
I have 3 tab bar items with 3 different view controller. 
And I use PMAlertController for the first tab item, it works great but whenever I select another tab item and go back to the first one it gives black screen. 

I think it may relate to super views and order of views . 

Thanks in advance for the great library.

<img width="282" alt="screen shot 2016-12-12 at 4 08 32 pm" src="https://cloud.githubusercontent.com/assets/17549441/21100446/c47294d2-c07c-11e6-8113-ddc515c8f1c8.png">
<img width="276" alt="screen shot 2016-12-12 at 4 08 47 pm" src="https://cloud.githubusercontent.com/assets/17549441/21100455/cee1c780-c07c-11e6-876d-c9250e188bb9.png">
<img width="290" alt="screen shot 2016-12-12 at 4 08 40 pm" src="https://cloud.githubusercontent.com/assets/17549441/21100461/d528ec36-c07c-11e6-8ee7-b0db1d7d120f.png">

**Comment by Codeido** [comment]
Hi @fadylateef.
Can you post the code here?

Thanks
-Paolo

**Comment by fadylateef** [comment]
I'm using an action when the red close button tapped .
Here's the code 

```
@IBAction func deleteTapped(_ sender: Any) {
        let alert = PMAlertController(title: "Delete History", description: "Do you really want to delete recent searches ?!", image: nil, style: .alert)
        alert.addAction(PMAlertAction(title: "Yes", style: .default, action: {kaka in
        self.deleteRecents()
        }))
        alert.addAction(PMAlertAction(title: "No", style: .cancel, action: nil))
        self.present(alert, animated: true, completion: nil)
    }

```

**Comment by Codeido** [comment]
Usually is not possibile to tap on another tab with PMAlertController showed.

I made a test project, and i don't have this type of error. Which controller is presenting PMAlertController?
[PMTabBarWithAlert.zip](https://github.com/Codeido/PMAlertController/files/646134/PMTabBarWithAlert.zip)

**Comment by Codeido** [comment]
Do you have some news about that?

**Comment by fadylateef** [comment]
I'm afraid , the same problem is standing.
Maybe I've used the alert controller in wrong order of views hierarchy .

Thanks for due care .

**Comment by mn288** [comment]
I have the same problem and it is not because of the view hierarchy. 
I was using PMAlertController from a subclass which then I call it from a the view in the tabbar. I tried  removing the subclass and directly calling PMAlertController, I can still press on any tabbar Item and sometimes the screen is black.
It was not doing the same behavior prior swift 3. I am not sure what the problem is for me.

**Comment by Codeido** [comment]
@mn288 if you try to use UIAlertController, do you have the same problem?

**Comment by fadylateef** [comment]
Tried on another project and it's working fine.
Using Xcode 8.2 beta and iOS 10.2.

**Comment by attheodo** [comment]
I have the same issue while presenting from a subclass

**Comment by akring** [comment]
Same problem here, I have to use this via:
```swift
guard let root = UIApplication.shared.keyWindow?.rootViewController else { return }
root.present(alert, animated: true, completion: nil)
```

**Comment by Burakpusat** [comment]
I was having the same issue. I was able to overcome the problem by the help of @akring above.
