### ISSUE TITLE
How to use with obj-c?

### ISSUE THREAD

**Issue by afiq90** [Codeido/PMAlertController#4]

**Comment by Codeido** [comment]
Hi @afiq90.

I've updated PMAlertController, and now Objective-C is supported. Please update your pod.

**How to use with obj-c:**
After the creation of a bridging header, use PMAlertController like this:
`  
   
    @import PMAlertController;

    
    PMAlertController *alert = [[PMAlertController alloc]initWithTitle:@"A Title" description:@"My Description" image:nil style:PMAlertControllerStyleAlert];
    
    [alert addAction:[[PMAlertAction alloc]initWithTitle:@"Cancel" style:PMAlertActionStyleCancel action:^{
        
    }]];
    
    [alert addAction:[[PMAlertAction alloc]initWithTitle:@"OK" style:PMAlertActionStyleDefault action:^{
        
    }]];
    
    [self presentViewController:alert animated:true completion:nil];`

**Comment by afiq90** [comment]
thank you dude.

**Comment by vsanthanam** [comment]
If anyone is looking for better Objective-C compatibility, I re-wrote this whole library from scratch in Objective-C, without using the XIB file. It's more "objective-c-ish", if that makes any sense, including support for a static (fat) library packaging. https://vsanthanam.github.io/VSAlertController/
