### ISSUE TITLE
Is there a way to prevent the popup to close ?

### ISSUE THREAD

**Issue by sennin31** [Codeido/PMAlertController#43]
Hello,

I am building a popup to login in my app, is there a way to prevent the popup to close, in order to tell the user that le credentials are wrong without showing another login popup ?

**Comment by Codeido** [comment]
Actually no, because every tap on a PMAlertAction calls the dismiss method. For your particular case, you can fork the project, and delete this line of code from  *PMAlertController.swift*: 

```
alertAction.addTarget(self, action: #selector(PMAlertController.dismissAlertController(_:)), for: .touchUpInside)
```

-Paolo

**Comment by kishykumar** [comment]
I ran into the same requirement @Codeido - don't want to dismiss the alert. 
The whole purpose of the textfield is to receive user input. If the input is invalid, seems to me like the error should be shown inside the alert view itself. 
We can fork, but upgrading to the latest version of this library won't be smooth.
