### ISSUE TITLE
PMAlertController hides in another view

### ISSUE THREAD

**Issue by forlearnios** [Codeido/PMAlertController#44]
I'm working with google maps the PMAlertController hides behind the map what could do to get it front? I'm stuck here.

**Comment by Codeido** [comment]
Can you show me the code?

- Paolo

**Comment by forlearnios** [comment]
func newPMAlert(){
        
        let alertVC = PMAlertController(title: "WITHOUT PHONE NUMBER", description: "You need to set your phone number in profile without phone number driver can't able to contact you", image: UIImage(named: "ic_cardss.png"), style: .alert) //Image by freepik.com, taken on flaticon.com
        
        alertVC.addAction(PMAlertAction(title: "Cancel", style: .cancel, action: { () -> Void in
            print("Cancel")
        }))
        
        alertVC.addAction(PMAlertAction(title: "Set now", style: .default, action: { () in
            print("Set now")
            
            let editProfileVC = ARMainEditProfileVC()
            self.homePassEditProfile = "No Phone Number Alert"
            editProfileVC.passEditProfile = self.homePassEditProfile
            self.navigationController?.pushViewController(editProfileVC, animated: true)
            
        }))
        
        self.present(alertVC, animated: true, completion: nil)
    }

**Comment by Codeido** [comment]
Are you sure that the alert is presented? If you are sure, check if the map is presented in a new view controller after the presentation of PMAlertController.

Let me know.
-Paolo

**Comment by forlearnios** [comment]
Both are present in the same viewController

**Comment by Codeido** [comment]
I need more information to understand where the problem is. Actually your implementation of the alert seems to be correct. If you can, please show me all the code of your view controller.

Thanks
-Paolo

**Comment by forlearnios** [comment]
the codes are too long to show....

**Comment by Codeido** [comment]
Without the code I can not help you :| sorry
