### ISSUE TITLE
Configuration Options?

### ISSUE THREAD

**Issue by alexjordaan** [Codeido/PMAlertController#47]
Hi! How do we change the font face and colors for the default and cancel styles?

**Comment by Codeido** [comment]
Hi @alexjordaan!

You can customize the alert action like a normal UIButton, in fact PMAlertAction is a subclass of UIButton.

Example:
```
let action = PMAlertAction(title: "Allow", style: .default, action: { () in
            print("Allow")
        })

action.setTitleColor(UIColor.green, for: .normal)
```

Thanks
-Paolo
