### ISSUE TITLE
Adding extra PMAlertActionStyle

### ISSUE THREAD

**Issue by yoavschwartz** [Codeido/PMAlertController#49]
I wanted to use `PMAlertAction` to imitate `UIAlertController`, with one difference, that is the ability to show an image above the title. However, I ran into multiple problems when trying to subclass.

`PMAlertAction` is marked as an `open class` signing that it should be welcoming to subclassing, but the problem is for example, `PMAlertActionStyle` is limited to 2 cases, `default` and `cancel` but I want to imitate the behaviour of the standard `UIAlertController` which means I also need `destructive`. 
Even if I wanted to replace `PMAlertActionStyle` with my own enum, I couldn't since `actionStyle` is a must have for initialisation. 

In addition `addSeperator` and `tapped` are internal, so if I don't want to re-write them, I must use the convenience initialiser, which again takes a `PMAlertActionStyle` and is also extremely "Opinionated" about the design. I wonder what other people do? since I see no choice but forking it and replacing the enum with my own.

It also seems to only be used in 2 places, the `init` to determine the `titleColor` and in the `animateDismissWithGravity`.

I would suggest `PMAlertActionStyleType` should be a protocol with a `var titleColor` and `var animationStyle`. `PMAlertActionStyle` can confirm to it, maintaining backwards compatibility. While letting other people extend it as needed, as expected from a UI framework.

I am of course aware that I can just crate a `PMAlertAction`, ignore the `PMAlertActionStyle`, change whatever I need in it and then return it, but it seems a little weird to do. Maybe it would make more sense if the `PMAlertActionStyle` had followed UIAlertController and had `destructive` with a default implementation the looked exactly like UIAlertController, so that a person could use a `PMAlertController` as plug and play replacement for for `UIAlertController`. However, as it stands with the yellow title and pinkish red button, it only fits into very specific designs and forces any user to customise it.

Otherwise though, I think it's really great, and a much needed framework, with UIAlertController being so rigid.

**Comment by Codeido** [comment]
Hi @yoavschwartz, thanks for open this issue. Do you have an image of the alert that you want to implement? I think that be more simple to understand.
I understand that you don't want to use a PMAlertAction, but you want to insert any view that can substitute a PMAlertAction, right?

For example, you want to drag a custom UIView that replace a PMAlertAction under the title, and you want to add inside every view what you want, is correct?

**Comment by yoavschwartz** [comment]
In fact, I just want to make something that looks exactly like UIAlertController, only with an image. 
![screen shot 2017-07-19 at 10 09 11](https://user-images.githubusercontent.com/12152339/28357077-7e050b20-6c6a-11e7-9187-318aa5a5199f.png)

**Comment by Codeido** [comment]
Then, you don't want the title and the description? 

Something like that?
![28357077-7e050b20-6c6a-11e7-9187-318aa5a5199f](https://user-images.githubusercontent.com/495617/28357971-700d4b2e-6c6d-11e7-9db1-d2e01778e703.png)

**Comment by PasqualePuzio** [comment]
Hi, is it possible somehow on release 3.5.0 to have an alert just with a custom view in the header and two buttons? Without title and description. Thanks

**Comment by pmusolino** [comment]
@PasqualePuzio yes sure, you can hide title and description.

**Comment by PasqualePuzio** [comment]
Great! I suppose that in order to hide title and description I just have to pass nil. Right?

**Comment by pmusolino** [comment]
No, you need to hide the labels. `.isHidden = true`

**Comment by PasqualePuzio** [comment]
Got it. Thank you!
