### ISSUE TITLE
Alert disappear

### ISSUE THREAD

**Issue by MattiaConfalonieri** [Codeido/PMAlertController#56]
I think that I found a little bug 

If You Call two alert in sequence:

First alert->ok call->second alert

the second alert disappear immediately and block the app with the only maskbackground visible.

If you delay the second alert call this don't happen.

Hope that my explanation is clear.

**Comment by Codeido** [comment]
How is the VC that present the alert, the old alert or the main vc?
Can you show me your implementation?

-Paolo

**Comment by MattiaConfalonieri** [comment]
Both alert are presented by the topView controller, same view controller.

**Comment by MattiaConfalonieri** [comment]
Hi, any news about this issue?

**Comment by Codeido** [comment]
Fixed [3.2.0](https://github.com/Codeido/PMAlertController/releases/tag/3.2.0).
Already available via Cocoapods.

**Comment by MattiaConfalonieri** [comment]
I love you ♥️😂
