### ISSUE TITLE
Feature request :)

### ISSUE THREAD

**Issue by YHSX88** [Codeido/PMAlertController#6]
Hi 

Can you implement "tap away" feature i.e. if the user taps outside of the PMAlert then to dismiss the Alert window.

Thanks in advance !

**Comment by Codeido** [comment]
Hi @YHSX88. 

I think that I do not need to put this in the library.

If you need this feature, you can access to the view or to alertMaskBackground of PMAlertController and add a gesture recognizer that dismiss the alert. Is really simple! 

If you need more help, i'm here.
Paolo
