### ISSUE TITLE
Got Error dependency `PMAlertController` is not used in any concrete target with pod 1.0.0

### ISSUE THREAD

**Issue by afiq90** [Codeido/PMAlertController#8]
Why did I get this error when running pod install command? 

**The dependency `PMAlertController` is not used in any concrete target.**

I'm using xcode 7.3 with objective-c project and pod version 1.0.0

Thanks in advance.

**Comment by Codeido** [comment]
Hi @afiq90. Please, update to pod version 1.0.3.
Objective-C is supported from the version 1.0.2.

Let me know.

**Comment by afiq90** [comment]
I tried to uninstall and install my pod but it still give me version 1.0.0, how can I update version 1.0.3?

**Comment by Codeido** [comment]
In your podfile, don't specify the version, like this:

`pod 'PMAlertController'`

then, call

`pod update` in Terminal.

Let me know.

**Comment by afiq90** [comment]
thank  you, after i ran pod update command, I tried pod install again and now it's successfully installed.
